### ISSUE TITLE
opencollective postinstall script causes failure on android

### ISSUE THREAD

**Issue by dominictarr** [Level/level#100]
@Luandro was trying to build our application (secure-scuttlebutt) on android, but had a problem with the opencollective postinstall script, https://github.com/flumedb/flumeview-level/pull/8#issuecomment-386741616

I also noticed another issue about this: https://github.com/Level/level/issues/94 it seems like in some system configurations, dev deps in `node_modules/.bin` are not available.

The solution might be as simple as `"postinstall": "opencollective postinstall || true"` so that the command always succeeds, even if it's somehow missing.

**Comment by vweevers** [comment]
Like #94, it's probably an npm issue. I like your solution though. The postinstall script should never interfere with installation.

> The solution might be as simple as "postinstall": "opencollective postinstall || true" so that the command always succeeds, even if it's somehow missing.

Or `|| exit 0` for Windows compatibility. Only Git Bash users will have `true`.

**Comment by ralphtheninja** [comment]
3.0.1
