### ISSUE TITLE
Segmentation fault in child thread with levelDB

### ISSUE THREAD

**Issue by genisgetman** [Level/level#117]
Version node: v10.8.0
Ubuntu 16

I see this error when i try connection to LevelDB in child thread from module 'worker_threads'
```
Ошибка сегментирования (сделан дамп памяти)
// Segmentation fault
```
This is the code that executes in eval field of thread:

```
const level = require('level')
const db = level('./data', {
  valueEncoding: 'json'
}, 
(error) => {
  if (error) { 
    console.log('LevelDB storage does not open with',error) }
  else { console.log('LevelDB storage has opened') }
})
```

Before this error with levelDB this threads performed any code even with Redis(almost the same levelDB), but with this case i getting the message that describes above.

**Comment by vweevers** [comment]
1. Does worker_threads (do you have a link?) use native threads?
2. Can you please provide a complete example that we can install?

**Comment by genisgetman** [comment]
Thank you for quick response!
Yes, this is the native threads of nodejs => https://nodejs.org/api/worker_threads.html 

For example, you will need to execute this JavaScript code after installing levelDB from npm:
`const { Worker } = require('worker_threads')

worker = new Worker(
  `const level = require('level')

  console.log('check the worker')

  const db = level('./data', {
    valueEncoding: 'json'
  }, 
  (error) => {
    if (error) { 
      console.log('LevelDB storage does not open with',error) }
    else { console.log('LevelDB storage has opened') }
  })`,
  {
    eval: true
  })
`

**Comment by vweevers** [comment]
> Yes, this is the native threads of nodejs => https://nodejs.org/api/worker_threads.html

Ah, never used that. @ralphtheninja @juliangruber do you have any experience with worker threads?

**Comment by ralphtheninja** [comment]
> @ralphtheninja @juliangruber do you have any experience with worker threads?

Nope, unfortunately not.

**Comment by peakji** [comment]
@genisgetman The new experimental worker threads module does not support native addons.

* https://nodejs.org/api/worker_threads.html#worker_threads_class_worker
> Native addons are not supported yet.

* https://gist.github.com/benjamingr/3d5e86e2fb8ae4abe2ab98ffe4758665#q-do-native-addons-work-cluster-child_processes
> Q: Do native addons work? Cluster? child_processes?
> A: not yet, but it is planned for the future. Launching child processes and clusters from workers is possible.

**Comment by peakji** [comment]
@genisgetman Btw, I don’t recommend using level in a Worker thread (except pure javascript stores like memdown) because leveldown handles async I/O it self.

In addition, the current "thread" implementation in node 10.x is not like threads in C++, the overhead of [structured clone](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) or ArrayBuffer serialization is innegligible.

* https://nodejs.org/api/worker_threads.html#worker_threads_worker_threads
> Workers are useful for performing CPU-intensive JavaScript operations; do not use them for I/O, since Node.js’s built-in mechanisms for performing operations asynchronously already treat it more efficiently than Worker threads can.
