### ISSUE TITLE
TypeScript types for level

### ISSUE THREAD

**Issue by alextes** [Level/level#120]
TypeScript complains it doesn't find types for this module.

Perhaps this issue can serve as a feature request or need for types.

Might it be as simple as a file explaining that this package is simply re-exporting `levelup` and `leveldown`?

**Comment by vweevers** [comment]
@Level/typescript

**Comment by sagaratalatti** [comment]
> @Level/typescript

npm ERR! 404 Not Found: @level/typescript@latest

**Comment by vweevers** [comment]
@sagaratalatti that's a GitHub team that I wanted to notify, they may be able to help with this issue.

**Comment by sagaratalatti** [comment]
@vweevers  okay the the tagged github team doesn't exist.

**Comment by vweevers** [comment]
Hm, is that team only visible to members @ralphtheninja?

**Comment by ralphtheninja** [comment]
Apparently so:

![screenshot from 2018-10-17 14-59-13](https://user-images.githubusercontent.com/308049/47087813-477c1980-d21d-11e8-890d-a3546937083f.png)

**Comment by MeirionHughes** [comment]
sorry for the awol - fighting off existential dread due to my (self-created) work-load - too many cogs. ;(

In principle this could be done simply as a reexport of ```LevelUp<Encoding>``` for now. Could do some more interesting things - like inferring key and value types from the codecs used at any stage - but I genuinely can't think about that at the moment.

**Comment by vweevers** [comment]
@MeirionHughes your health comes first, no apologies necessary. Thanks for checking in!

**Comment by bradoyler** [comment]
Ok, so this was added: https://www.npmjs.com/package/@types/level-js 
so I think a note needs to be added to the README on how it should be used...

**Comment by danielfx90** [comment]
Hi, I submitted a PR at DefinitelyTyped, feel free to review it! Thanks!!

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52198

**Comment by vweevers** [comment]
Thanks @danielfx90! The discussion can continue there, I'm closing this.

If documentation is needed here, PRs are welcome.
