### ISSUE TITLE
Tweak the description on OpenCollective

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level#126]
It was written by OpenCollective and it could be better.

https://opencollective.com/level

For example, it ends with the sentence:

> For a richer set of data types you can wrap the store with encoding-down.

This just sounds odd, since `level` _contains_ `encoding-down`.

**Comment by vweevers** [comment]
> It was written by OpenCollective

I doubt that. I vaguely recall Julian wrote/copy-pasted it, but that's not important.

> This just sounds odd, since `level` _contains_ `encoding-down`.

IMO the OpenCollective description shouldn't even focus on the `level` package specifically. Instead describe the ecosystem as a whole. If it has a generic description then we could link to it from every package.

**Comment by vweevers** [comment]
For reference, here's the current description:

---

**Level is a Node.js library and community for creating embedded databases - think SQLite, but non relational!**

It was first and foremost inspired by [LevelDB](https://github.com/google/leveldb), a simple key-value store built by Google. It's used in Google Chrome and many other products. LevelDB supports arbitrary byte arrays as both keys and values, singular get, put and delete operations, batched put and delete, bi-directional iterators and simple compression using the very fast [Snappy](http://google.github.io/snappy/) algorithm.

The way you iterate over a LevelDB makes it very usable for a myriad of use cases! LevelDB stores entries sorted lexicographically by keys, which makes the [streaming interface](https://opencollective.com/level#createReadStream) of `levelup` that exposes LevelDB iterators as [Readable Streams](https://nodejs.org/docs/latest/api/stream.html#stream_readable_streams) a very powerful query mechanism.

It's flexible in another major respect, that is that the underlying storage backends are swappable! The most common store is [leveldown](https://github.com/level/leveldown/) which provides a pure C++ binding to LevelDB. [Many alternative stores are available](https://github.com/Level/awesome/#stores) such as [level.js](https://github.com/level/level.js) in the browser or [memdown](https://github.com/level/memdown) for an in-memory store. They typically support strings and Buffers for both keys and values. For a richer set of data types you can wrap the store with [encoding-down](https://github.com/level/encoding-down).

**Comment by vweevers** [comment]
Idea: add the same description to `community` (so we can tweak the text together in a PR). That readme can use a few tweaks anyway, including a better description of the scope/purpose of that repo, which we haven't really discussed yet.

**Comment by vweevers** [comment]
Updated.
