### ISSUE TITLE
How to judge whether the database is empty when it is first used?

### ISSUE THREAD

**Issue by songdangwei** [Level/level#156]
Use db.get to show that 'Key not found in database'.
what should I do?

**Comment by songdangwei** [comment]
After the program starts, if the database does not exist, perform the refresh task.

**Comment by vweevers** [comment]
There are a few ways, like `db.iterator({ limit: 1 })`, `db.createReadStream({ limit: 1 })` or just checking whether the directory on disk exists (unless you are using `level` in the browser).

But a simpler solution might be to store something like the last refresh time in the db.

**Comment by songdangwei** [comment]
well done.

**Comment by songdangwei** [comment]
very well
