### ISSUE TITLE
promises

### ISSUE THREAD

**Issue by royalcala** [Level/level#164]
hello, the db.get doesnt return a promise, if the id doesnt find, you must to use promise before and use a callback. Is this the correct library?, I see that there are many libraries like  levelup(leveldown), this is a library level(levelup(leveldown), this one is the newest or recommended top of composition?, thanks best regards

**Comment by vweevers** [comment]
Most folks use `level` - it's the most convenient package. It supports promises since 2.0.0.

You can also use `levelup` by itself, and compose your own database. `levelup` supports promises since 2.0.0.

**Comment by vweevers** [comment]
I assume your thumbs up means good to close.
