### ISSUE TITLE
You can't save Classes

### ISSUE THREAD

**Issue by CHarcoalToast** [Level/level#166]
When you want to save classes to a level storage, it simply doesn't save.

Maybe you can apply a fix for this/another solution?

And if this is valid, maybe state it on the main page?

**To reproduce**:
```js
// I know, not the best example
const level = require('level');
const db = level('pathtostorage')

class AnyClass {}
var myclass = new AnyClass()
db.put('test', myclass)
db.put('test2', "Test"

```
When you'd get all the values in the storage, it will only get the second one, the first one isn't even added.

Maybe I'm wrong...

**Comment by vweevers** [comment]
You can save objects by using the json encoding:

```js
const level = require('level')
const db = level('my-db', { valueEncoding: 'json' })

await db.put('test', { foo: 123 })
```

**Comment by CHarcoalToast** [comment]
Now I have a problem with the streams: when I do createValueStream().on('data', data => console.log(data)), it logs 'null', but when I get it with the get() method, it works.
.

**Comment by vweevers** [comment]
Can you share a complete code example?
