### ISSUE TITLE
[Question] How could I query a list of the stored keys?

### ISSUE THREAD

**Issue by almosnow** [Level/level#168]
Self-explanatory.

Is there some kind of db.list( ... ) method?

**Comment by almosnow** [comment]
Ok I found out.

**Comment by astutesoftware** [comment]
> Self-explanatory.
> 
> Is there some kind of db.list( ... ) method?



> Ok I found out.

and how was that?

**Comment by almosnow** [comment]
Use createReadStream:

https://github.com/Level/level#createReadStream
