### ISSUE TITLE
Unable to install on macOS Catalina with Node.js v12.8.0

### ISSUE THREAD

**Issue by zeke** [Level/level#176]
Hello. I'm getting errors when trying to `npm install level@latest`. 

Here's are the first few lines:

```
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.3/fse-v1.2.3-node-v72-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.2.3 and node@12.8.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
```

And the full node-gyp output here: https://gist.github.com/zeke/f3c1c34560348ea80313d515d7ce7e92

Environment:

```
$ node --version
v12.8.0

$ uname -a
Darwin zekes-mbp.lan 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

FWIW I do think I have my compiler tools set up properly, as I am able to install other native modules like `node-sass` without issue: https://gist.github.com/zeke/9bae8a305e180d7cf288738d9815b11c

Thanks for any guidance!

**Comment by vweevers** [comment]
It appears you have `leveldown@4` elsewhere in your node_modules, which doesn't support node 12.

**Comment by zeke** [comment]
Hey that fixed it. I assumed that `npm install level@latest` would just disregard whatever already existed in package.json, but apparently not. 🤔 

Thanks, @vweevers ✨
