### ISSUE TITLE
Using in serverless function

### ISSUE THREAD

**Issue by rrrepos** [Level/level#191]
Is there a manner in which the db path can be a remote path as in a cloud file. This is to explore running the level engine on a serverless function like Google Functions or AWS Lamda.

**Comment by vweevers** [comment]
You might like [`multileveldown`](https://github.com/Level/multileveldown) and [similar modules](https://github.com/Level/awesome#shared-access).

**Comment by rrrepos** [comment]
Thanks @vweevers will check them out
