### ISSUE TITLE
`createReadStream` not giving expected results when getting data from existing db

### ISSUE THREAD

**Issue by DrFacepalm** [Level/level#193]
I am using typescript. I have previously created a db using the following:
```ts
import level from 'level';

async function test() {
  const db = await level("./tmp/leveltest");

  await db.put("key", "value");
  await db.put("cat", "vooloo");
  await db.put("car", "valiant");
  await db.put("kerb", "vat");

  await db.close();
}

test();
```

That runs fine, and I am then able to do:

```ts
import level from 'level';

async function test() {
  const db = await level("./tmp/leveltest");

  console.log(await db.get("key"));
  console.log(await db.get("cat"));
  console.log(await db.get("car"));
  console.log(await db.get("kerb"));

  await db.close();
}

test();
```

and it prints the correct results.

However, how am i supposed to get a list of all the keys in a db without reffering to them by name individually?

I have attempted this:
```ts
async function test() {
  const db = await level("./tmp/leveltest");

  db.createKeyStream()
    .on('data', function (data) {
      console.log(data);
    })

  await db.close();
}
```

but it only prints `car` instead of all the keys. 
* I have also attempted to use the iterator, but it seems to give a lot of 'undefined' values
* I have also attempted to call `resume()` on the stream before but it gives the same result

How am I supposed to fetch all keys, values or all data from an existing database?

**Comment by ralphtheninja** [comment]
And TIL that you can do `backtics` in a github issue title :smile:

**Comment by DrFacepalm** [comment]
(Sorry for the slow reply), but ahh that makes sense. Since I don't want to necessary close the db, I've done this to read all keys asynchronously.

```ts
async function test() {
  const db = await level('./tmp/leveltest');

  await new Promise<void>((resolve, reject) => {
    db.createKeyStream()
      .on('data', (data) => {
        console.log(data);
      })
      .on('end', async () => {
        resolve;
      });
    reject;
  });

  await db.close();
}
```
