### ISSUE TITLE
About opening and closing the database

### ISSUE THREAD

**Issue by brenoh1ldebr4nd** [Level/level#197]
<p>Hey, awesome community! How u doing?</p>

From the docs about **close()**: 
> **You should always** clean up your levelup instance by calling close() when you no longer need it to free up resources.

and also from the docs about **open()**:
> However, it is possible to reopen the store after it has been closed with close(), **although this is not generally advised.**

<p>So If I got it, I should open the database using <b>level()</b> to execute some operations and, as soon as possible, I should close it using <b>close()</b>. What about after that, when I need to execute some more operations? What is the best way to reopen it and close it again?!</p>

**Comment by ralphtheninja** [comment]
It doesn't say you should close it as soon as possible. Maybe this wording could be better.

**Comment by vweevers** [comment]
Something like:

> A `levelup` instance has associated resources like file handles and locks. When you no longer need your `levelup` instance (for the remainder of your program) call `close()` to free up resources.

**Comment by brenoh1ldebr4nd** [comment]
So I should open it once and keep it open till my app don't need it anymore. Is that right?

**Comment by brenoh1ldebr4nd** [comment]
Great! So @vweevers, that sounds good!
