### ISSUE TITLE
Auto Generated Unique Key

### ISSUE THREAD

**Issue by rupamking1** [Level/level#199]
if anyone save data generate automatically unique key, is that now possible with leveldb?

**Comment by vweevers** [comment]
Multiple solutions exist for this. Depends on several factors: how do you want your keys to be sorted, should they be globally unique, are your writes random or sequential, do you delete keys and if so do you want to allow reuse, etc. This is all up to you.

Can you be more specific?

**Comment by rupamking1** [comment]
@vweevers I want globally unique & sequential, it may delete and reuse.

**Comment by vweevers** [comment]
Using [`ulid`](https://github.com/ulid/javascript) as keys may work for you. E.g.:

```js
const ulid = require('ulid').monotonicFactory()

await db.put(ulid(), 'example')
```

**Comment by rupamking1** [comment]
ulid() will this package never genarate same id

**Comment by vweevers** [comment]
> ulid() will this package never genarate same id, every time will it genarate unique id?

It has 80 bits of randomness (see [spec](https://github.com/ulid/spec)). Should be sufficiently unique, but that's your call.

> Can i use uniqid/nanoid/uuid package for Maintaining Global Uniqueness?

The benefit of `ulid` is that the generated ids sort lexicographically and increase monotonically. If you [stream](https://github.com/Level/level#createReadStream) or iterate keys from your db, you get them back in insertion order.

**Comment by rupamking1** [comment]
1. Yes, I understood but this repository not upgrade till 2019, Can you please a recently upgraded repository?

**Comment by vweevers** [comment]
Sequential, for sure.

**Comment by rupamking1** [comment]
@vweevers Please answer my questions

> 1. Yes, I understood but this repository not upgrade till 2019, Can you please a recently upgraded repository?
> 2. leveldb performance is High in sequential key or in random key, which one make leveldb performance better?

**Comment by vweevers** [comment]
Your tone is too demanding - also in https://github.com/ulid/javascript/issues/88 - and I frankly don't feel like explaining why that is an issue. So I'm just gonna leave this thread until you realize it yourself. Good luck!

**Comment by rupamking1** [comment]
@vweevers Extremely sorry for my word, you are so helpful, Thank You for Helping me.

**Comment by vweevers** [comment]
Thank you! To answer your first question:

> Yes, I understood but this repository not upgrade till 2019, Can you please a recently upgraded repository?

`ulid` is stable as far as I know, and dependency-free, so naturally it's light on maintenance. I don't know of other UUID generators that sort in the same way, but I'm sure they can be found.

For inspiration, you might want to look at [`flakeid`](https://github.com/casualjim/flakeid) (written in Go but conceptually relevant), [`monotonic-lexicographic-timestamp`](https://github.com/vweevers/monotonic-lexicographic-timestamp) (only unique per-machine, not globally) and modules listed in [awesome](https://github.com/level/awesome#data-structures).

Lastly, you can of course write your own solution, which has the benefit that you can optimize it for your specific use case. For example, let's say you have a cluster of machines and you already have a known distinct name for each machine, then you could construct keys in the form of `<timestamp>~<name>` or `<sequence number>~<name>`.
