### ISSUE TITLE
Raplica & Sharding

### ISSUE THREAD

**Issue by hanumanjiblog** [Level/level#200]
How to replicate and split level database?
Please tell us, we really need replication.

**Comment by vweevers** [comment]
For replication, see https://github.com/Level/awesome#replication. Most of the modules listed there are old though. You might be better off with a dedicated solution that doesn't rely on `level`, like [`hypercore`](https://github.com/hypercore-protocol/hypercore) and friends.

For splitting, see [`subleveldown`](https://github.com/Level/subleveldown).

**Comment by hanumanjiblog** [comment]
Please Tell us Is any c or c++ LevelDB is available nodejs?

**Comment by vweevers** [comment]
I don't understand the question.

**Comment by ralphtheninja** [comment]
> Please Tell us Is any c or c++ LevelDB is available nodejs?

`level` itself uses `leveldown` which is a c++ wrapper lib around `LevelDB`.
