### ISSUE TITLE
Insert Lock, Read Lock, Dead Lock Concatency Control

### ISSUE THREAD

**Issue by omymy1** [Level/level#202]
Future Request- Please implement Insert Lock, Update Lock, Read Lock, Dead Lock etc Concatency Control.
because if two user want to update same key value then it makes problem. Please add this feature is already implemented then let me know.

**Comment by vweevers** [comment]
See prior discussions: https://github.com/Level/levelup/issues/691, https://github.com/Level/community/issues/47, https://github.com/Level/levelup/issues/133, https://github.com/Level/levelup/issues/381.

And prior art: https://github.com/Level/awesome#atomicity.

**Comment by omymy1** [comment]
Is that feature already implemented or not please answer me?
