### ISSUE TITLE
[Question] how can "level-js" make data persistence?

### ISSUE THREAD

**Issue by Moon1102** [Level/level#208]
When I develop a vscode plugin(used vscode WebView Api), I use `level` to save some data.
 Then I found the data will be saved to `IndexedDB`  and  it works great.
BUT When I reopen plugin,the data all missed，even because of the isolation mechanism of vscode WebView, the data stored in page A cannot be obtained in page B....
 Unlike in the `node` project,all data will be saved in local files.

How can I make data persistence? Can `level-js` save data to local files?

I would appreciated if someone can give me any advice.

**Comment by vweevers** [comment]
I'm not familiar with vscode internals but it sounds like you need a Node.js-like context (if that's available in vscode). Then `level` would use LevelDB instead of IndexedDB. Alternatively, check if you can make the session of the webview persistent.

**Comment by Moon1102** [comment]
okay,perhaps webview send the data to the plugin first and then being processed and stored by the plugin is a possible way. Thanks a lot. I'll try it later.
