### ISSUE TITLE
db.isOperational is not a function

### ISSUE THREAD

**Issue by XfedeX** [Level/level#210]
I installed Level with npm install level, and I am using it like this:
/src/db.js:
```js
const level = require("level");
const db = level("./save");

module.exports.put = db.put;
module.exports.get = db.get;
module.exports.del = db.del;
```
/index.js:
```js
const db = require("./src/db");
db.put("username", "example!",(err,data)=>{
  if (err) return console.error(err)
})
```
I am getting the error `db.isOperational is not a function`.

**Comment by ralphtheninja** [comment]
@XfedeX I suspect you're missing the `this` pointer when exporting `put`, `get` and `del`. Does the following work?

```js
const level = require('level')
const db = level('./save')

module.exports.put = db.put.bind(db)
module.exports.get = db.get.bind(db)
module.exports.del = db.del.bind(db)
```

**Comment by XfedeX** [comment]
> @XfedeX I suspect you're missing the `this` pointer when exporting `put`, `get` and `del`. Does the following work?
> 
> ```js
> const level = require('level')
> const db = level('./save')
> 
> module.exports.put = db.put.bind(db)
> module.exports.get = db.get.bind(db)
> module.exports.del = db.del.bind(db)
> ```
> 
> Why don't you just do e.g.:
> 
> ```js
> const level = require('level')
> module.exports = level('./save')
> ```
> 
> ?

Thanks, this fixes the issue.
