### ISSUE TITLE
npm install level - fails on Windows 8.1, node 0.12 npm 2.5.1

### ISSUE THREAD

**Issue by HansS** [Level/level#22]
C:\Users\Hans\web\node\level\level-me>npm install level -f
npm WARN using --force I sure hope you know what you are doing.
npm WARN package.json sqlite@1.0.4 Invalid filename in 'files' list:
-

> leveldown@0.10.5 install C:\Users\Hans\node_modules\level\node_modules\leveldown
> node-gyp rebuild

\
C:\Users\Hans\node_modules\level\node_modules\leveldown>node "C:\Users\Hans\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn c:/Python2.7/python ENOENT
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
gyp ERR! stack     at child_process.js:1137:20
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\Hans\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Hans\node_modules\level\node_modules\leveldown
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\Hans\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "level" "-f"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package generator-karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer generator-angular@0.10.0 wants generator-karma@>=0.8.2
npm ERR! peerinvalid Peer generator-tsangular@0.1.5 wants generator-karma@~0.4.0

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Hans\web\node\level\level-me\npm-debug.log

C:\Users\Hans\web\node\level\level-me>

**Comment by juliangruber** [comment]
doesn't look like a level related problem, since it's failing installing sqlite and that's none of level's dependencies. maybe can you share the .dependencies section of your package.json?
