### ISSUE TITLE
Recommended way of retrieving a list of all keys?

### ISSUE THREAD

**Issue by faustbrian** [Level/level#220]
Been wondering what's the recommended way of getting a list of all keys in a database. I'm currently doing the following:

```js
const result = [];

for await (const [key, _] of database.iterator({ keys: true, values: false })) {
    result.push(key);
}

return result;
```

This feels a bit hacky. Is there any way to do this more efficiently or dump all keys at once?

**Comment by vweevers** [comment]
```js
const result = await db.keys().all()
```
