### ISSUE TITLE
Types do not export `destroy` property

### ISSUE THREAD

**Issue by MicaiahReid** [Level/level#224]
The level types do not export a `Level.destroy` property, even though the property does exist on Level. This leads to type errors when using `Level.destroy`.

**Comment by vweevers** [comment]
From the README:

> TypeScript type declarations are included and cover the methods that are common between `classic-level` and `browser-level`.

Although both `classic-level` and `browser-level` happen to have a `destroy()` method, it's not part of the `abstract-level` interface and their function signatures differ.
