### ISSUE TITLE
Random "Error: Database is not open" errors

### ISSUE THREAD

**Issue by ppedziwiatr** [Level/level#229]
Hey, I'm getting random `Error: Database is not open` errors, both in jest test and on production code.
```
Error: Database is not open
at maybeError (node_modules/abstract-level/abstract-level.js:806:27)
      at ClassicLevel.batch (node_modules/abstract-level/abstract-level.js:520:9)
      at TrieLevel.batch (src/cache/impl/TrieLevel.ts:47:25)
```      

level: 8.0.0
nodejs: v18.12.1
macOS Ventura 13.1

I'm 100% that there's no concurrent access to LevelDB.

The code that is using the Level (it's basically a c/p from https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/trie/recipes/level.ts):
```ts
import { MemoryLevel } from 'memory-level';

import type { BatchDBOp, DB } from '@ethereumjs/trie';
import type { AbstractLevel } from 'abstract-level';

const ENCODING_OPTS = { keyEncoding: 'buffer', valueEncoding: 'buffer' };

export class TrieLevel implements DB {
  readonly _leveldb: AbstractLevel<string | Buffer | Uint8Array, string | Buffer, string | Buffer>;

  constructor(leveldb?: AbstractLevel<string | Buffer | Uint8Array, string | Buffer, string | Buffer> | null) {
    this._leveldb = leveldb ?? new MemoryLevel(ENCODING_OPTS);
  }

  async get(key: Buffer): Promise<Buffer | null> {
    let value: Buffer | null = null;
    try {
      // await this._leveldb.open();
      value = await this._leveldb.get(key, ENCODING_OPTS);
    } catch (error: any) {
      // https://github.com/Level/abstract-level/blob/915ad1317694d0ce8c580b5ab85d81e1e78a3137/abstract-level.js#L309
      // This should be `true` if the error came from LevelDB
      // so we can check for `NOT true` to identify any non-404 errors
      if (error.notFound !== true) {
        throw error;
      }
    } finally {
      // await this._leveldb.close();
    }
    return value;
  }

  async put(key: Buffer, val: Buffer): Promise<void> {
    // await this._leveldb.open();
    await this._leveldb.put(key, val, ENCODING_OPTS);
    // await this._leveldb.close();
  }

  async del(key: Buffer): Promise<void> {
    // await this._leveldb.open();
    await this._leveldb.del(key, ENCODING_OPTS);
    // await this._leveldb.close();
  }

  async batch(opStack: BatchDBOp[]): Promise<void> {
    // await this._leveldb.open();
    await this._leveldb.batch(opStack, ENCODING_OPTS);
    // await this._leveldb.close();
  }

  copy(): DB {
    return new TrieLevel(this._leveldb);
  }
}
```

The commented-out manual `open`/`close` calls also do not fix the issue.
I've also tried leaving only the `open` calls (without manual `close` calls) - this also does not help.

How should I fix this issue?

Is there a way to have a fully manual control over when the level db connection is opened and closed?

It seems to do some kind of auto opening/closing trickery, that simply doesn't work in this case.

**Comment by ppedziwiatr** [comment]
Those errors also happen in a browser env.

**Comment by vweevers** [comment]
Can you please provide a complete example that reproduces the issue, written in JavaScript?

**Comment by ppedziwiatr** [comment]
I will try to prepare a MRE, in the meantime - is there an option to have a fully manual control over when the db is being opened and closed?

The above issue simply blocks us from using the leveldb in production and a manual control would be (at least temporarily) a great option for us.

**Comment by vweevers** [comment]
> is there an option to have a fully manual control over when the db is being opened and closed?

```js
// Opens the db automatically
const db = new Level()
```

```js
const db = new Level()

// Open the db manually, one tick before Level would do this
await db.open()
```

There's no code on this side that automatically closes the db, so either something on your side calls `db.close()`, or opening fails to begin with - and in that case `db.open()` might tell you why.

**Comment by vweevers** [comment]
> even with manual calls to open()/close() before/after each operation

I don't know. That might be a bug, but need an MRE to find out what's happening.

**Comment by ppedziwiatr** [comment]
> There's no code on this side that automatically closes the db, so either something on your side calls `db.close()`, or opening fails to begin with - and in that case `db.open()` might tell you why.

is it possible to try-catch an error from `await db.open()` - or do I need to use version with a callback?

**Comment by vweevers** [comment]
> is it possible to try-catch an error from `await db.open()`

Yes. As an example, if you were to open the db from a second process in parallel, you'd get:

```js
try {
  await db.open()
} catch (err) {
  console.error(err.code) // 'LEVEL_DATABASE_NOT_OPEN'

  if (err.cause && err.cause.code === 'LEVEL_LOCKED') {
    // Another process or instance has opened the database
  }
}
```

**Comment by ppedziwiatr** [comment]
Thanks.

Last question - the issue started to occur after we've added a 2nd `level` db instance to our app (each one of them is created via a separate `new Level()` or `new MemoryLevel()`).

Is there a chance that `level` holds some 'global' state which somehow affects are the databases are opened/closed?

**Comment by vweevers** [comment]
Level instances cannot use the same location. So `new Level('./a'); new Level('./b')` is fine (and there is no state shared between them) but `new Level('./a'); new Level('./a')` will not work. You can use [`rave-level`](https://github.com/Level/rave-level) for that purpose.

**Comment by ppedziwiatr** [comment]
I'm not using the same location...

The location of the 1st db is `${DEFAULT_LEVEL_DB_LOCATION}/state/`
The location of the 2nd db is `${DEFAULT_LEVEL_DB_LOCATION}/kv/${contractDefinition.txId}`

Also - the issue does not occur when both databases are of `MemoryLevel` type.

**Comment by vweevers** [comment]
Have a look at the `err.cause` property on your second instance, like https://github.com/Level/level/issues/229#issuecomment-1367876085 does.

**Comment by vweevers** [comment]
Note that you could also use sublevels - e.g. `db.sublevel('state')` and `db.sublevel('tx')` - instead of two separate locations, although I'd first like to get to the bottom of this issue in case there's a bug.

**Comment by ppedziwiatr** [comment]
> Have a look at the `err.cause` property on your second db, like [#229 (comment)](https://github.com/Level/level/issues/229#issuecomment-1367876085) does.

Yeah, this was helpful - turned out the 2nd. db was initialized twice and 2nd time the `LEVEL_LOCKED` err.cause has shown.

From the devex perspective - it would be great if the `cause` was shown in the original error by default.

Thanks for your time and help!

Re. sublevels - I'm already using sublevels for the 1st database. Since the 2nd serves a completely different purpose (and keeps data in a different format, encoding, etc) - I've decided to split them into separate databases/files.

**Comment by vweevers** [comment]
> it would be great if the `cause` was shown

There was a Node.js issue about that (because `cause` is [standardized](https://github.com/tc39/proposal-error-cause)) but I cannot find it just now.
