### ISSUE TITLE
semver for level?

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level#27]
Since `level` is a convenience module wrapping `level-packager` and `leveldown` the version number will hardly ever change due to changes to level itself, i.e. the version basically depends on the version of  its dependencies.

How should we do this properly? I guess if `levelup` changes major then `level-packager` also will change major and then it seems logical to me that `level` should do the same.

But how should the version of `leveldown` affect this module? Right now I've updated `leveldown` to `1.2.2`, so would that always mean updating patch?

**Comment by mcollina** [comment]
This very same problem is relevant to [level-browserify](http://npm.im/level-browserify) too, with the added problem of level-js.

I propose a general rule: level* tracks the MAJOR.MINOR of levelup, but it depends using `^` against leveldown. This minimizes the number of releases, given that we just need to release leveldown for any nan bumps.

**Comment by ralphtheninja** [comment]
+1 That makes sense.

**Comment by juliangruber** [comment]
I'd say release a `PATCH` if there's a fix that in any way can relate to a user, release a `MINOR` if the public api has a new feature, and release a `MAJOR` if the public api changed.

**Comment by juliangruber** [comment]
With a leveldown `MINOR` release, it depends most of the times on whether we consider `db.db` to be a public interface. I vote for yes, since we already refer to `db.db.approximateSize` etc

**Comment by mcollina** [comment]
@juliangruber you are speaking about PATCH releases: are you assuming to depend on fixed versions of levelup and leveldown here? PATCH releases here won't happen so often (what can go wrong?) if we use `~` or `^`.

I am ok for a stricter application of semver, like @juliangruber described, but then level versions will probably diverge from levelup. We tried to maintain the same version numbers for quite some time.

I am ok for changing this to a more stricter versioning, but then we will have to release all level* much more often. So, it is more burden to maintain the stuff.

**Comment by ralphtheninja** [comment]
If we look at the code. I mean this is *all* this module does:

```js
module.exports = require('level-packager')(require('leveldown'))
```

`level` has the same api as `level-packager` and obviously that goes for `level-hyper` as well. With this in mind, it seems to me that `level` should track (at least) MAJOR.MINOR of `level-packager`.

**Comment by ralphtheninja** [comment]
With that said I guess this boils down to what @mcollina just mentioned. Do we want to be pragmatic or not? :) I personally don't mind a more stricter approach and today it's a lot easier for us to publish new versions since @rvagg has given access to me and @juliangruber.

**Comment by juliangruber** [comment]
i personally don't care whether `level` and `levelup` stay the same version

**Comment by ralphtheninja** [comment]
Me either. I did `1.1.0` for now and lets see how it goes :)

**Comment by mcollina** [comment]
Same here, but we need to document it anyway.
