### ISSUE TITLE
Module version mismatch. Expected 43, got 14

### ISSUE THREAD

**Issue by sergiovilar** [Level/level#28]
Hi, I'm getting this error when triyng to use Level with Electron.

Could someone help me? Thanks.

**Comment by ralphtheninja** [comment]
@sergiovilar Hi. Could you please post the output of `npm i --verbose`? It's probably too large to paste here to make a gist and link to it. Thanks.

**Comment by ralphtheninja** [comment]
This feels like an error with prebuilt binaries, but we need more information to correct it. cc @mafintosh

**Comment by mafintosh** [comment]
@sergiovilar are you getting this error after rebuilding level with apm? unfortunately you need to this because electron embeds their own node runtime. see https://github.com/moose-team/friends/blob/master/package.json#L96 for an example on how to do this

@ralphtheninja i don't think this is related to prebuilds

**Comment by sergiovilar** [comment]
@mafintosh I'm not triyng to rebuild level, I just installed and tried to use :/

**Comment by sergiovilar** [comment]
BTW I tried to rebuild with no success:

Ran this:

```HOME=~/.electron-gyp node-gyp rebuild --target=0.25.0 --arch=ia64 --dist-url=https://atom.io/download/atom-shell````

And got this:

```
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild" "--target=0.27.2" "--arch=ia64" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd /Users/sergiovilar/hh/plugin-desktop/public/node_modules/leveldown
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok``

**Comment by sergiovilar** [comment]
Hi guys, I finally got leveldown built using leveldown 1.0.5 and levelup 1.0.0-3.

**Comment by ralphtheninja** [comment]
@sergiovilar Which versions of `leveldown` and `levelup` did *not* work?

**Comment by sergiovilar** [comment]
@ralphtheninja the latest on npm!

**Comment by tgaherwar** [comment]
hi. I am getting the same error, along with the message: ATOM_SHELL_ASAR.js:137
 Uncaught Error: Module version mismatch. Expected 44, got 14
@sergiovilar how did you resolve it?

**Comment by sergiovilar** [comment]
@tgaherwar I didn't, I gave up to use leveldb with electron

**Comment by juliangruber** [comment]
I think this is a pretty important use case, so we should get this to work

**Comment by ralphtheninja** [comment]
:+1:

**Comment by juliangruber** [comment]
everyone, please check https://github.com/Level/electron-demo/issues/1

**Comment by pekeler** [comment]
I'm getting the same error with this simple use case.

```bash
> npm init -y
> npm i level --save
> node -e "require('level')"
/tmp/rocksbtest/node_modules/level/node_modules/leveldown/node_modules
/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/tmp/rocksbtest/node_modules/level/node_modules/level
down/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/tmp/rocksbtest/node_modules/level/node_mod
ules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:570:32)
```
