### ISSUE TITLE
How to get a leveldown instance when installed with level?

### ISSUE THREAD

**Issue by binarykitchen** [Level/level#3]
Is there a chance to get a leveldown instance when LevelDB has just been installed with `npm install level --save`?

Something like

```
var leveldown = require('level').leveldown;
```

?

**Comment by ralphtheninja** [comment]
Should be documented in [`packager`](https://github.com/Level/packager)

**Comment by ralphtheninja** [comment]
https://github.com/Level/packager/issues/18
