### ISSUE TITLE
Tricky architectural question: How to circumvent the LOCK issue when running multiple instances?

### ISSUE THREAD

**Issue by binarykitchen** [Level/level#30]
I have a problem here with the LevelDB nature that it locks the database, preventing other processes to access it. Let me explain:

I have a nodejs server running, opening one LevelDB instance and piping data all the time for a high-traffic site. Then I have a weekly cron, calling another piece of code with `node clean.js` which is supposed to clean the database once a week, i.E. removing expired database entries. And that won't work, always getting the `OpenError: IO error` because the server instance is locking it.

Previously I did this with `wget -qO /dev/null https://videomail.io/clean` triggering the cleaning process but that's not so nice for lots of reasons. I prefer to call this directly on the server with `node clean.js`

How can I solve this? Do I have to add code on the server instance to receive signals from another node process? For me this adds unnecessary complexity. Wondering if you LevelDB guys ever have dealt with similar cases and how you solved it?

**Comment by dominictarr** [comment]
Simplest would be to put the clean job inside the main server, and trigger it via a http route (or something)
also, there is level-party https://github.com/substack/level-party

The one-process limitation is essential to the design of leveldb it self--that is the part that makes it easy to embed.

**Comment by ralphtheninja** [comment]
You could use signals, so the server could listen to e.g. `SIGHUP` and then clean up.

**Comment by binarykitchen** [comment]
@dominictarr totally understand and respect leveldb's one-process limitation. guess this is one small disadvantage of leveldb. triggering the clean job via a http route on a local server has the smell to overcomplicate things for many reasons: additional nginx config and needs timeout handling (since the clean job might take minutes).

... but i think i ll give https://github.com/substack/level-party a try - but one thing worries me: data loss. it says that disabling snapshotting "will not retry streams / gets / puts if the leader goes down" ... is this really safe as it says?

@ralphtheninja could try with `SIGHUP` but i do not like to idea to override default process signals. furthermore i prefer the clean job to be able to run on its own without relying on main server process.

**Comment by dominictarr** [comment]
@binarykitchen basically, he means that if you have a read stream and the party's host crashes, that read stream will just error. It probably doesn't matter in your case, because i bet your cleanup will have the same result if it is restarted part way through, right? or if you accidentially ran two cleanups that would still be okay?

Tbh, level-party will have more code running on your server, although the interface won't be as complicated...

**Comment by binarykitchen** [comment]
true @dominictarr, the clean job is idempotent, safe to be called multiple times. but what if it takes over the leveldb instance as the new party host and crashes for whatever reason? the other server process (in my case, the videomail.io server) might loose data while users are recording videos over write streams straight to the level db ...

(yes, i'm aware that more code from level-party isn't nice but at this prototypical stage i prefer to keep things as simple as possible by avoiding unnecessary complexity)

**Comment by dominictarr** [comment]
@binarykitchen well, the gc process cannot take over unless the main process crashes first, so you'd have that problem anyway. Its like saying "what if I write a bug"? maybe I should just stay in bed?
You are gonna write bugs, and things will crash... and getting out of bed in the morning means admitting this, how can we lessen the impact of those mistakes?

I suspect that this particular problem (server crashing) can't be fixed from the server, but _can_ be mitigated from the client. You can program the client to retry those operations... or at least, present the user with a sensible error message, and let them retry, or email you, etc.

**Comment by binarykitchen** [comment]
yeah, right ... i get your message @dominictarr - alright, since videomail.io already comes with a good error mechanism, i ll give level-party a try then. thanks for your good advice!

**Comment by binarykitchen** [comment]
tried level-party today but got a `Error: Connection to leader lost`:
https://github.com/substack/level-party/issues/8

looks like the party host takeover didn't work out, hmmm ...
