### ISSUE TITLE
gyp ERR! configure error

### ISSUE THREAD

**Issue by artur99** [Level/level#31]
Kind of tried everything... :(
npm-debug.log: http://pastebin.com/w1UpGRz9

Latest error on cmd:
D:\Host_njs>npm install level
        npm WARN package.json tanking@1.0.0 No repository field.
        npm WARN package.json tanking@1.0.0 No README data
        npm WARN installMany node-pre-gyp was bundled with leveldown@1.3.0, but bundled
        package wasn't found in unpacked tree
        |
        > leveldown@1.3.0 install D:\Host_njs\node_modules\level\node_modules\leveldown
        > node-pre-gyp install --fallback-to-build

    D:\Host_njs\node_modules\level\node_modules\leveldown>if not defined npm_config
    node_gyp (node "C:\Programs\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\nod
    _modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )
    
    D:\Host_njs\node_modules\level\node_modules\leveldown>if not defined npm_config
    node_gyp (node "C:\Programs\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\nod
    _modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=D:\Ho
    t_njs\node_modules\level\node_modules\leveldown\build-pre-gyp\leveldown.node --
    odule_name=leveldown --module_path=D:\Host_njs\node_modules\level\node_modules\
    eveldown\build-pre-gyp --python=/usr/bin/python2 )  else (node  configure --fal
    back-to-build --module=D:\Host_njs\node_modules\level\node_modules\leveldown\bu
    ld-pre-gyp\leveldown.node --module_name=leveldown --module_path=D:\Host_njs\nod
    _modules\level\node_modules\leveldown\build-pre-gyp --python=/usr/bin/python2 )
    
    gyp ERR! configure error
    gyp ERR! stack Error: Can't find Python executable "/usr/bin/python2", you can
    et the PYTHON env variable.
    gyp ERR! stack     at failNoPython (C:\Programs\nodejs\node_modules\npm\node_mo
    ules\node-gyp\lib\configure.js:114:14)
    gyp ERR! stack     at C:\Programs\nodejs\node_modules\npm\node_modules\node-gyp
    lib\configure.js:69:11
    gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
    gyp ERR! System Windows_NT 6.3.9600
    gyp ERR! command "node" "C:\\Programs\\nodejs\\node_modules\\npm\\node_modules\
    node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\Hos
    _njs\\node_modules\\level\\node_modules\\leveldown\\build-pre-gyp\\leveldown.no
    e" "--module_name=leveldown" "--module_path=D:\\Host_njs\\node_modules\\level\\
    ode_modules\\leveldown\\build-pre-gyp" "--python=/usr/bin/python2"
    gyp ERR! cwd D:\Host_njs\node_modules\level\node_modules\leveldown
    gyp ERR! node -v v0.12.5
    gyp ERR! node-gyp -v v2.0.1
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fall
    ack-to-build --module=D:\Host_njs\node_modules\level\node_modules\leveldown\bui
    d-pre-gyp\leveldown.node --module_name=leveldown --module_path=D:\Host_njs\node
    modules\level\node_modules\leveldown\build-pre-gyp --python=/usr/bin/python2' (
    )
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Host_njs\node_modul
    s\node-pre-gyp\lib\util\compile.js:83:29)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proce
    s.js:1087:5)
    node-pre-gyp ERR! System Windows_NT 6.3.9600
    node-pre-gyp ERR! command "node" "D:\\Host_njs\\node_modules\\node-pre-gyp\\bin
    \node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd D:\Host_njs\node_modules\level\node_modules\leveldown
    node-pre-gyp ERR! node -v v0.12.5
    node-pre-gyp ERR! node-pre-gyp -v v0.6.7
    node-pre-gyp ERR! not ok
    Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\Host_
    js\node_modules\level\node_modules\leveldown\build-pre-gyp\leveldown.node --mod
    le_name=leveldown --module_path=D:\Host_njs\node_modules\level\node_modules\lev
    ldown\build-pre-gyp --python=/usr/bin/python2' (1)
    npm ERR! Windows_NT 6.3.9600
    npm ERR! argv "C:\\Programs\\nodejs\\\\node.exe" "C:\\Programs\\nodejs\\node_mo
    ules\\npm\\bin\\npm-cli.js" "install" "level"
    npm ERR! node v0.12.5
    npm ERR! npm  v2.11.2
    npm ERR! code ELIFECYCLE
    
    npm ERR! leveldown@1.3.0 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the leveldown@1.3.0 install script 'node-pre-gyp install --f
    llback-to-build'.
    npm ERR! This is most likely a problem with the leveldown package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-pre-gyp install --fallback-to-build
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls leveldown
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     D:\Host_njs\npm-debug.log

I have Python 3.4 and Windows 8.1

Thanks you...

**Comment by ralphtheninja** [comment]
You could try doing `npm i leveldown@1.2.2` because it has prebuilt binaries for windows.

**Comment by ralphtheninja** [comment]
Oh sorry, you were using `level`. Then you can instead try `npm i level@1.1.0`. If I'm not mistaken that will try grabbing `leveldown@1.2.2` and hopefully that'll work better for you.

**Comment by No9** [comment]
Hi @artur99 The top of the log mentions 
> gyp ERR! stack Error: Can't find Python executable "/usr/bin/python2", you can
et the PYTHON env variable.

If the suggestion from @ralphtheninja doesn't work out can you open a command prompt and provide the output from the command 

```
echo %PYTHON%
```

It should tell you the location of the python exe 

Thanks

**Comment by artur99** [comment]
@ralphtheninja 's command gave me the same error: http://pastebin.com/DvMtCbRN
for `echo %PYTHON%` I get this: `C:\Programs\Python34\python.exe`

**Comment by ralphtheninja** [comment]
Oh okay, it seems related to python as @No9 suspected. It seems it's trying to locate python from `"/usr/bin/python2"` which is kind of odd. Are you using cygwin on windows or something like that?

It's also stupid that you need python for this at all, but that's a whole other discussion :)

**Comment by ralphtheninja** [comment]
Hmm and I think you need to have python 2 and not 3. But not sure.

**Comment by No9** [comment]
Yeah @artur99 looks like python 2.7 is required 
https://github.com/TooTallNate/node-gyp/blob/master/README.md#installation 
Please can you install 2.7 and rerun
Thanks

**Comment by artur99** [comment]
Is there going to be a new version that supports Py3?

**Comment by ralphtheninja** [comment]
> Is there going to be a new version that supports Py3?

I'm afraid that's out of the scope of this thread. You need python 2.7 to make it work. For now.
