### ISSUE TITLE
Help review levelmeup workshopper update

### ISSUE THREAD

**Issue by rvagg** [Level/level#40]
@Level/owners @martinheidegger has done an amazing job of updating levelmeup to use the latest workshopper which should allow it to stay more current and even include translations. If anyone in here has time to cast an eye over it, even if it's just running it to make sure that it does what's expected, that would be really great. It's a pretty important piece of the level\* ecosystem as it helps with onboarding but it's become a bit stale. https://github.com/workshopper/levelmeup/pull/79

Also, if you're interested in helping maintain it and keeping it updated I'm pretty sure you'd be welcomed with open arms!

**Comment by ralphtheninja** [comment]
I'll def check it out!
