### ISSUE TITLE
IO Error in packaged Electron app

### ISSUE THREAD

**Issue by gerhardberger** [Level/level#41]
I'm making an Electron app with LevelDB and want to use asar in packaging, but at startup it gives this error:

```
Uncaught Exception:
OpenError: IO error: ./hypershare.db/LOCK: No such file or directory
    at /Users/gerhard/dev/node/hypershare-app/dist/Hypershare-darwin-x64/Hypershare.app/Contents/Resources/app.asar/node_modules/levelup/lib/levelup.js:119:34
    at /Users/gerhard/dev/node/hypershare-app/dist/Hypershare-darwin-x64/Hypershare.app/Contents/Resources/app.asar/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```

I tried to unpack the file that creates the db, so it isn't in the `.asar` file, but it gives the same error.

If I don't use asar it works though.

How could I avoid this error?

**Comment by BrunoBernardino** [comment]
Hi @gerhardberger! I recently came across this issue in https://github.com/nolanlawson/pouchdb-electron/issues/9 but not using `asar` isn't working for me as well, did you end up solving this?

**Comment by ralphtheninja** [comment]
@gerhardberger Mind sharing some code on how you initialize levelup in your code?

**Comment by BrunoBernardino** [comment]
@ralphtheninja Not sure if you wanted to ask me (it's in the issue I linked), but it's a very standard [`new PouchDB('blah')`](https://github.com/BrunoBernardino/Oikon2-Mac/blob/master/utils/DataDB.js#L18), when electron [calls the `renderer`](https://github.com/BrunoBernardino/Oikon2-Mac/blob/master/renderer.js#L17).

**Comment by ralphtheninja** [comment]
@BrunoBernardino I suspect this is related to your db not being ready while doing `this.expensesDB.createIndex()`. I haven't used pouch myself but maye you could try something like

```js
PouchDB.on('created', dbName => {
  if (dbName === EXPENSES_URI) {
    this.expensesDB.createIndex({
      index: {
        fields: ['name', 'date'],
      },
    })
    this.expensesDB.createIndex({
      index: {
        fields: ['type'],
      }
    })
  }
})
```

And similar logic for `TYPES_URI`.

**Comment by BrunoBernardino** [comment]
I'll try that later today, though the app works fine with and without data before packaging, so I suspect that's not the case. I'll let you know.

**Comment by BrunoBernardino** [comment]
Nope. I commented the whole section of creating indexes and the error was the same. 😕

**Comment by BrunoBernardino** [comment]
Is there a way to confirm in which directory it's trying to get the files?

**Comment by ralphtheninja** [comment]
> Is there a way to confirm in which directory it's trying to get the files?

You would have to browse the PouchDB code for that, but shouldn't be too hard to find I think.

**Comment by BrunoBernardino** [comment]
Indeed I fixed it by "forcing" the directory (somewhere it wasn't being set properly, _after_ packaging): https://github.com/BrunoBernardino/Oikon2-Mac/pull/2/files#diff-0aa32d546cef508ec48190878d4d7f50R17

**Comment by ralphtheninja** [comment]
> Indeed I fixed it by "forcing" the directory (somewhere it wasn't being set properly, after packaging): https://github.com/BrunoBernardino/Oikon2-Mac/pull/2/files#diff-0aa32d546cef508ec48190878d4d7f50R17

Happy you managed to solve it! Closing this issue, if you don't mind :)

**Comment by Alecyrus** [comment]
@BrunoBernardino  Bro, could you please give me more details? I set `database` in my electron app (render process) like this:
```javascript
const path = require('path');
const db = new PouchDB(path.join(__dirname, 'database'));
console.log(path.join(__dirname, 'database'));
```

But I still got the error after packaging..
![image](https://user-images.githubusercontent.com/13865581/52196812-2e64aa80-2898-11e9-830e-f70cde3c6560.png)

**Comment by BrunoBernardino** [comment]
@Alecyrus here's the relevant code (sorry, that repo/app got sold and is no longer publicly available):

```js
// renderer.js
const { remote } = require('electron');
const { app } = remote;
const appName = 'Oikon 2';
const appData = `${app.getPath('appData')}/${appName}`;

// This is in another file, but I've simplified for this showcase purpose here
const database = new PouchDB(`${appData}/database`);
```

Basically the main problem here was PouchDB couldn't access that app location, but electron can access the `appData` path, which will depend on the OS.

I hope that helps!

**Comment by Alecyrus** [comment]
@BrunoBernardino Thanks, but It seems not work. Maybe I need to create the `database` directory before initializing the `pouchDB` ?
```javasciript
const { app } = remote;
const appName = 'Vaquita';
const appData = `${app.getPath('appData')}/${appName}`;
const db = new PouchDB(`${appData}/database`);
```

**Comment by ralphtheninja** [comment]
@Alecyrus Take care that you aren't trying to open the same location twice. This is what theh `LOCK` file signals.

**Comment by Alecyrus** [comment]
Thank you, @ralphtheninja . Yeah, I found it.  Actually @BrunoBernardino 's answer have solved my problem. Thanks, bro. But I did not notice that I run `electron:serve` and open the packaged app at the same time.
