### ISSUE TITLE
TypeError on initialization in strict mode

### ISSUE THREAD

**Issue by dcousens** [Level/level#42]
``` sh
$ node --version
v7.4.0
```
``` js
$ node --use-strict
> require('level')
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode
functions or the arguments objects for calls to them
    at CustomError (TEST/node_modules/errno/custom.js:18:44)
    at createError (TEST/node_modules/errno/custom.js:42:43)
    at ce (TEST/node_modules/errno/custom.js:48:12)
    at module.exports (TEST/node_modules/errno/custom.js:52:25)
    at Object.<anonymous> (TEST/node_modules/errno/errno.js:312:44)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by dcousens** [comment]
This effectively limits me from using `levelup` on particular `strict` deployments

**Comment by ralphtheninja** [comment]
@dcousens Maybe open up an issue on https://github.com/rvagg/node-errno

**Comment by dcousens** [comment]
Probably should close in favour of https://github.com/rvagg/node-errno/issues/17,  but,  its been open since March D:

**Comment by dcousens** [comment]
@ralphtheninja what is the likelihood of that being fixed?

**Comment by ralphtheninja** [comment]
@dcousens I have no idea. I just checked `errno` repository yesterday and it seems there are multiple issues related to this.

ping @rvagg

**Comment by dcousens** [comment]
@ralphtheninja thoughts on next steps?  Maybe email @rvagg ?

**Comment by ralphtheninja** [comment]
> @ralphtheninja thoughts on next steps? Maybe email @rvagg ?

Yes.

**Comment by ralphtheninja** [comment]
@dcousens Worst case scenario, fork `errno` and publish a new `errno2` module or something like that. This could also be a temporary solution that we can merge to upstream.

**Comment by dcousens** [comment]
`errno-strict`

**Comment by ralphtheninja** [comment]
@dcousens I'm cleaning up stuff and trying to cut loose ends for upcoming version of `level`. Do we need to do something in `level` for this to work out for you? Please re-open and comment in that case.

**Comment by dcousens** [comment]
@ralphtheninja I stopped using `levelup` in favour of plain `leveldown` as a result.  Ended up easier anywy.

**Comment by rvagg** [comment]
Can someone (that I know, which includes both folks in these threads but includes many others of course) volunteer to take over `errno` for me? I have the guilt of a package with backed up PRs and issues that I can't justify the time investment in maintaining right now.

**Comment by ralphtheninja** [comment]
@dcousens Rod have given me access to `node-errno` now, so if you have any input and feedback please post some issues :)
