### ISSUE TITLE
Please update leveldown to latest (1.7.1)

### ISSUE THREAD

**Issue by JamesKyburz** [Level/level#46]
So we can get the prebuilt goodness of `https://github.com/level/leveldown/releases/download/v1.7.1/leveldown-v1.7.1-node-v57*`

**Comment by ralphtheninja** [comment]
It uses `~1.7.0` so should come automatically once leveldown is released

**Comment by JamesKyburz** [comment]
Thanks @ralphtheninja, was sleeping there :) had noticed leveldown commit and prebuilt files....didn't check npm .

**Comment by ralphtheninja** [comment]
@JamesKyburz The release and the prebuilts are out of sync for a while, so we wait until the prebuilts have been compiled before doing `npm publish`

**Comment by JamesKyburz** [comment]
@ralphtheninja Good to know, I won't be so trigger happy in the future ;)
