### ISSUE TITLE
release level-packager 2.0.0

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level#51]
But release `levelup@2.0.0` first ;)

**Comment by zixia** [comment]
Why do we need `level-packager` here?

It seems just a wrapper for `levelup`. If so, what's the point to do this? Can we merge it to the `level` module to let the code simpler?

Sorry for cannot figure it out by myself. Thanks!

**Comment by ralphtheninja** [comment]
It's a convenience module for being reused when packaging different *down memory stores/backends e.g. in `level`, `level-mem`, `level-rocksdb` etc.

**Comment by ralphtheninja** [comment]
See https://www.npmjs.com/browse/depended/level-packager for more usages of it

**Comment by zixia** [comment]
Got it. Thanks!
