### ISSUE TITLE
specify node engine in package.json for v2

### ISSUE THREAD

**Issue by aoberoi** [Level/level#54]
hey there,

i just gave v2.0.0-rc2 a shot because i was interested in the promise based API. i hit a runtime issue with destructuring assignment syntax. turns out i'm on node 4 and this isn't going to work. i noticed that levelup [has the engine specified in package.json](https://github.com/Level/levelup/blob/30883c5961b34c9620a976b19de9c38deb52c725/package.json#L70-L72), but i think this package should, too.

**Comment by aoberoi** [comment]
potentially related: https://github.com/npm/npm/issues/17778

**Comment by ralphtheninja** [comment]
@aoberoi Good catch!

**Comment by ralphtheninja** [comment]
See level/packager and level/levelup
