### ISSUE TITLE
readme tweaks

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level#59]
- [x] badges, see levelup (remember to close https://github.com/Level/level/issues/54 when node version badge has been added)
- [x] LevelUP/LevelDOWN -> `levelup`/`leveldown`
- [x] copy over API-section from levelup (start with hardcoded, we can extract to template later on for simplified/automated maintenance when api is updated) (remember to close https://github.com/Level/level/issues/9)
- [x] general styling, **Level** -> `level` etc

**Comment by ralphtheninja** [comment]
See WIP on this branch.

**Comment by vweevers** [comment]
@ralphtheninja Nice work!

The short description could use some tweaking too:

> A convenience package that bundles the current release of levelup and leveldown and exposes levelup on its export.

The "exposes levelup on its export" bit is confusing. It should make it clear that `level()` returns a `levelup` instance. This is not immediately obvious atm. Perhaps we can make a split in the README between `level()` and the levelup API?

**Comment by ralphtheninja** [comment]
> The "exposes levelup on its export" bit is confusing. It should make it clear that level() returns a levelup instance. This is not immediately obvious atm. Perhaps we can make a split in the README between level() and the levelup API?

I agree. But don't exactly know what you mean by the split. Would you mind making a PR? :)

**Comment by vweevers** [comment]
Nevermind the split, wouldn't work anyway. Rephrasing the short description should be enough. I didn't give any thought to the exact words yet.
