### ISSUE TITLE
Uncaught Error: The specified procedure could not be found.

### ISSUE THREAD

**Issue by zerooverture** [Level/level#71]
OS: window 7
node: v8.9.1
npm: v5.6.0

Uncaught Error: The specified procedure could not be found. XXX\node_modules\leveldown\build\Release\leveldown.node
in require('level')

**Comment by ralphtheninja** [comment]
Which version of level?

**Comment by zerooverture** [comment]
level version 2.1.0
Because of the Electron version of the problem,I have solved him.
prebuild -t 1.7.9 -r electron ,I used 1.2.5.
