### ISSUE TITLE
increase a value in one

### ISSUE THREAD

**Issue by mikzuit** [Level/level#83]
I 'm trying to add to a number 1 so I use my code like this below , but is adding the number 1 at the end instead . ex.  if currentVisits is 10 + 1 =  101. I'm also using together with then-levelup to
   promisify so ... 

```
const db = promisify(level('visits.db',{
    valueEnconding: 'json'
}))
...
try {
    const currentVisits = await db.get(pathname)
    await db.put(pathname, currentVisits + 1 )
  } catch (error) {
    if (error.notFound) await db.put(pathname, 1)
  }
```

but when I do this: 

```
try {
    const currentVisits = await db.get(pathname)
    await db.put(pathname, currentVisits - 1 )
  } catch (error) {
    if (error.notFound) await db.put(pathname, 1)
  }
```

Is actually subtracting 1 . ex: if current visits is 10 - 1 = 9

**Comment by juliangruber** [comment]
latest level supports promises out of the box, does it happen with this and without promisify still?

**Comment by vweevers** [comment]
`valueEnconding` should be `valueEncoding`.

**Comment by mikzuit** [comment]
Thanks @vweevers  that solve the problem , and I swear a check that part and I use it specifically because can store numbers. Still wonder why subtract correctly.

**Comment by vweevers** [comment]
That's a JS thing. The plus operator prefers strings, the minus operator prefers numbers.

```
> '9' + 1
'91'     
> '9' - 1
8
```
