### ISSUE TITLE
Update to level 2.0

### ISSUE THREAD

**Issue by finnp** [Level/level#84]
Hey,

I'm trying to update this repository to level 2.0 https://github.com/finnp/similar-issues-bot. If I just update the dependency I get encoding problems. 

I suspect the problem is that subleveldown is using levelup 1.0.

Maybe someone has an idea and help out?

**Comment by vweevers** [comment]
Yeah, subleveldown is not compatible with level(up) v2. No one has invested time in that yet (and subleveldown isn't in the level org). Want to help out? See also https://github.com/Level/community/issues/14.

**Comment by finnp** [comment]
Updating subleveldown worked 👍 PR is here: https://github.com/mafintosh/subleveldown/pull/7
