### ISSUE TITLE
release level

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level#85]

**Comment by ralphtheninja** [comment]
I'd like to release this as a new major, due to `leveldown` inheriting breaking changes for `.batch()` in `abstract-leveldown@4.0.0`.

**Comment by ralphtheninja** [comment]
@vweevers WDYT?

**Comment by vweevers** [comment]
Makes sense to me.

**Comment by vweevers** [comment]
Or wait. It's not a breaking change in `levelup`, so... hmm. oof

**Comment by ralphtheninja** [comment]
It's a breaking change in the underlying store, e.g. `leveldown`.

**Comment by vweevers** [comment]
`levelup` will already throw if you do `db.batch([null])`. In other words, yes, `leveldown` had a breaking change, but it's negated by `levelup`.

Unless people reach down into `db.db` - which I guess is a pretty common thing to do?

**Comment by vweevers** [comment]
> levelup will already throw if you do db.batch([null]). In other words, yes, leveldown had a breaking change, but it's negated by levelup.

That's kinda circumstantial though. I think I'm on board with a major release :)

**Comment by ralphtheninja** [comment]
> levelup will already throw if you do db.batch([null]). In other words, yes, leveldown had a breaking change, but it's negated by levelup.

Aaah, didn't think of this.
