### ISSUE TITLE
copy documentation to the level readme

### ISSUE THREAD

**Issue by substack** [Level/level#9]
Considering that `level` is now what most people `npm install`, it would make sense to copy the documentation (perhaps by script?) over from the levelup readme. This way the methods are well documented and handy without having to know that levelup is used internally by the level package.

**Comment by ralphtheninja** [comment]
Lets take care of this after `levelup@1.0.0` has been released!

**Comment by ralphtheninja** [comment]
@rvagg Hmm. Would publishing the c++ leveldb code to npm be a good idea? `leveldown` could then use that code from npm rather than keeping a separate copy of it in its history. Other modules could then use that code as well instead of bundling it, e.g. `ldb` by @hij1nx

**Comment by rvagg** [comment]
doable I guess, use a similar approach to nan, although nan is much simpler, just a header file
