### ISSUE TITLE
'opencollective' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by eslachance** [Level/level#94]
I think it's awesome to be opting in to opencollective, but while installing level, I ran into things that weren't very user-friendly. 

First, I had to install it under an administrator powershell (or command prompt I suppose would work). I don't recall ever having to do that on a project-level installation for node. Once I'd done that, I got the error that opencollective wasn't recognized as a program. So I had to `npm i -g opencollective` just to be able to be told "thanks for using level! please donate!"

It seems a little counterintuitive to require a global installation of a module just to request donations after the package is installed - otherwise the package just doesn't install because it fails on postinstall.

**Comment by eslachance** [comment]
I should probably indicate why I had to install as admin. I got the following error when attempting to simply `npm i level` under a regular user: 
```
npm ERR! path D:\home\devel\enmap-level\node_modules\wrappy\package.json.3545084894
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'D:\home\devel\enmap-level\node_modules\wrappy\package.json.3545084894' -> 'D:\home\devel\enmap-level\node_modules\wrappy\package.json'
npm ERR!  { Error: EPERM: operation not permitted, rename 'D:\home\devel\enmap-level\node_modules\wrappy\package.json.3545084894' -> 'D:\home\devel\enmap-level\node_modules\wrappy\package.json'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, rename 'D:\home\devel\enmap-level\node_modules\wrappy\package.json.3545084894' -> 'D:\home\devel\enmap-level\node_modules\wrappy\package.json'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'rename',
npm ERR!      path: 'D:\\home\\devel\\enmap-level\\node_modules\\wrappy\\package.json.3545084894',
npm ERR!      dest: 'D:\\home\\devel\\enmap-level\\node_modules\\wrappy\\package.json' },
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'D:\\home\\devel\\enmap-level\\node_modules\\wrappy\\package.json.3545084894',
npm ERR!   dest: 'D:\\home\\devel\\enmap-level\\node_modules\\wrappy\\package.json',
npm ERR!   parent: 'enmap-level' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
```

**Comment by ralphtheninja** [comment]
> It seems a little counterintuitive to require a global installation of a module just to request donations after the package is installed - otherwise the package just doesn't install because it fails on postinstall.

It's not required. `level` is using `opencollective` the same way as any other project. It seems to me the problems you are having is due to a problem with permissions.

**Comment by juliangruber** [comment]
I agree, this looks like an npm issue

**Comment by eslachance** [comment]
> It's not required. level is using opencollective the same way as any other project. It seems to me the problems you are having is due to a problem with permissions.

I have never used any other project that uses opencollective, and thus, I did not have it installed. I feel my point stands: if you're going to require the installation of a global third-party module and fail to install without it, you should at least point that out in the requirements part of your readme. Perhaps I should PR this part to the readme to be more helpful to some users?

**Comment by ralphtheninja** [comment]
As I said. A global installation of opencollective is not required.

**Comment by juliangruber** [comment]
@ralphtheninja is right, npm isn't tryint to install this tool locally for you, it will install it into `./node_modules/.bin/` and call it from there.

You see, this is the particular file that npm complains about not being able to rename: `D:\home\devel\enmap-level\node_modules\wrappy\package.json`.

We can't help debug npm setups here unfortunately, please create an issue at github.com/npm/npm.

**Comment by mdanial07** [comment]
Install npm i -g opencollective.
Then install npm install --save opencollective-postinstall 

its work for me
