### ISSUE TITLE
Upgrading level to v2

### ISSUE THREAD

**Issue by Siilwyn** [Level/level#98]
Hi there, I'm upgrading from `1.7.0` to `2.1.2` at [this small project](https://github.com/Siilwyn/cheers-receiver) and get the following error:

```
  Error {
    message: 'constructor requires a location string argument',
  }

  LevelDOWN.AbstractLevelDOWN (node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:12:11)
  new LevelDOWN (node_modules/leveldown/leveldown.js:14:21)
  LevelDOWN (node_modules/leveldown/leveldown.js:12:12)
  Level (node_modules/level-packager/level-packager.js:13:27)
  Object.create (test/helpers/database.js:11:18)
  Test.test.beforeEach.t [as fn] (test/validation.js:9:31)
```

Think because it's missing the `location` parameter, at [the following code](https://github.com/Siilwyn/cheers-receiver/blob/d31cc7a7f81d175bf8a70938a62578d39b196e17/src/main.js#L7): `leveldb(process.env.LEVELDOWN_DB || require('memdown'));`

How would I achieve this in version 2?

**Comment by ralphtheninja** [comment]
Your code should work out of the box. I suspect `process.env.LEVELDOWN_DB` should be a string but not defined? `level()` constructor takes a string.

**Comment by vweevers** [comment]
@Siilwyn side note, you don't need `database.get = promisify(database.get)`. See https://github.com/Level/level#promise-support

**Comment by Siilwyn** [comment]
@ralphtheninja thanks for the fast reply, sorry for the confusion, it actually fails on this line:
`leveldb({ db: memdown })`

@vweevers that was not the case when I worked with `level` as far as I can remember, guess that's new?

**Comment by vweevers** [comment]
> cheers! That was not the case when I worked with level as far as I can remember, guess that's new?

Yes :)

> thanks for the fast reply, sorry for the confusion, it actually fails on this line:
leveldb({ db: memdown })

Ah. So no, this code doesn't work out of the box. Because `level` is a convenience package specifically for `leveldown`, and doesn't take a custom store (such as `memdown`). If you want swappable stores, you'll want to use `levelup`:

```js
const levelup = require('levelup')
const leveldown = require('leveldown')
const memdown = require('memdown')
const encode = require('encoding-down')

// With leveldown
const db = levelup(encode(leveldown('./db1')))

// With memdown (latest version)
const db = levelup(encode(memdown())))
```

**Comment by vweevers** [comment]
Alternatively, you can use `level-mem`, a similar convenience package, but for `memdown`.

**Comment by ralphtheninja** [comment]
So this code never worked? :)

**Comment by Siilwyn** [comment]
@vweevers ah thanks for the clarification, going to give it a spin tomorrow.

@ralphtheninja well it works with version `1.7.0`, something changed going to version 2... I'm using it in 'production' and both my tests locally and for example [the latest CI run](https://travis-ci.org/Siilwyn/cheers-receiver/builds/373172837) is passing. So something changed but I guess it was not intended to work, while it did.

**Comment by ralphtheninja** [comment]
@Siilwyn I see now why it works

`v1.7.0` of level uses `level-packager@1.2.0` which does:

```js
const levelup = require('levelup')

function packager (leveldown) {
  function Level (location, options, callback) {
    if (typeof options === 'function')
      callback = options
    if (!(typeof options === 'object' && options !== null))
      options  = {}

    options.db = leveldown

    return levelup(location, options, callback)
  }

  [ 'destroy', 'repair' ].forEach(function (m) {
    if (typeof leveldown[m] === 'function') {
      Level[m] = function (location, callback) {
        leveldown[m](location, callback || function () {})
      }
    }
  })

  return Level
}

module.exports = packager
```

Here `location` corresponds to `{ db: memdown }` in your case, which is passed down to `levelup()` which will use that as a backend. Afaict this was not intended, but worked because `levelup` had this functionality.

Now `level-packager` does:

```js
const levelup = require('levelup')
const encode = require('encoding-down')

function packager (leveldown) {
  function Level (location, options, callback) {
    if (typeof options === 'function') {
      callback = options
    }
    if (typeof options !== 'object' || options === null) {
      options = {}
    }

    return levelup(encode(leveldown(location), options), options, callback)
  }

  [ 'destroy', 'repair' ].forEach(function (m) {
    if (typeof leveldown[m] === 'function') {
      Level[m] = function (location, callback) {
        leveldown[m](location, callback || function () {})
      }
    }
  })

  Level.errors = levelup.errors

  return Level
}

module.exports = packager
```

Which is more unforgiving, since `location` really has to be a string.

**Comment by Siilwyn** [comment]
Thank you all for your helpful & detailed responses! :heart:
Really like being able to swap out memdown and leveldown, perfect for testing.

If anybody is interested these are the changes I made to update: https://github.com/Siilwyn/cheers-receiver/pull/4
